[project]
name = "target"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "carla==0.9.12",
    "dictor>=0.1.12",
    "einops>=0.8.1",
    "ephem>=4.2.1",
    "filelock>=3.16.1",
    "gym>=0.26.2",
    "h5py>=3.11.0",
    "hydra-core==1.1",
    "lmdb==1.8.1",
    "lxml>=6.1.1",
    "matplotlib>=3.7.5",
    "munch>=4.0.0",
    "networkx==2.2",
    "numpy==1.20",
    "omegaconf==2.1.2",
    "openai==0.28",
    "opencv-python==4.2.0.32",
    "pickle-mixin>=1.0.2",
    "psutil>=7.2.2",
    "py-trees==0.8.3",
    "pygame>=2.6.1",
    "pyyaml>=6.0.3",
    "ray==2.5",
    "requests>=2.32.4",
    "scipy>=1.10.1",
    "shapely==2.0.6",
    "simple-watchdog-timer>=0.1.1",
    "six>=1.17.0",
    "sympy>=1.13.3",
    "tabulate>=0.9.0",
    "tqdm>=4.68.3",
    "wandb>=0.24.2",
    "xmlschema==1.0.18",
]
