[project]
name = "target"
version = "0.1.0"
description = "STADSUNT's TARGET fork"
readme = "README.md"
authors = [
    { name = "JarukitMan", email = "jarukit.man@student.mahidol.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "antlr4-python3-runtime==4.10",
    "carla>=0.9.16",
    "ephem>=4.2.1",
    "graphviz>=0.21",
    "matplotlib>=3.11.1",
    "networkx==3.4.2",
    "numpy>1.24.4 ; python_full_version >= '3'",
    "opencv-python==4.7.0.72",
    "psutil>=7.2.2",
    "py-trees==0.8.3",
    "pygame>=2.6.1",
    "shapely==2.1.1",
    "simple-watchdog-timer>=0.1.1",
    "six>=1.17.0",
    "tabulate>=0.10.0",
    "xmlschema==1.0.18",
]

[project.scripts]
target = "target:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
